name: GriefPreventionEasyGUI
version: '1.3'
main: org.hope.griefPreventionEasyGUI.GriefPreventionEasyGUI
api-version: '1.21'
depend: [GriefPrevention]

commands:
  claimhelp:
    description: Opens a grief prevention help GUI.
    usage: /claimhelp
  gpegui-reload:
    description: Reloads the GriefPreventionEasyGUI configuration.
    usage: /gpegui-reload
    permission: gpegui.admin
